version: '3'
services:
  # backend:
  #     container_name: backend
  #     restart: always
  #     build: ./backend/
  #     depends_on:
  #       postgres-database:
  #         condition: service_healthy
  #       # kong-migration:
  #       #   condition: service_started
  #     links:
  #       - postgres-database:postgres-database
  #     ports:
  #       - 8080:8000
  #     environment:
  #       - VITE_DB_HOST=postgres
  #       - VITE_IP_ADDR=0.0.0.0
  #       - VITE_PORT=8080
  #       - VITE_LOGS_DIR=logs/
  #       - VITE_DB_PORT=5433
  #       - VITE_DB_USER=clickers
  #       - VITE_DB_PASS=clickers
  #       - VITE_DB_NAME=clickers


  # postgres-database:
  #   image: postgres:15-alpine
  #   container_name: postgres-database
  #   environment:
  #       - POSTGRES_USER=clickers
  #       - POSTGRES_PASSWORD=clickers
  #       - POSTGRES_DB=clickers
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5


  # kong-migration:
  #   image: backend
  #   container_name: kong-migration
  #   depends_on:
  #     postgres:
  #         condition: service_healthy
  #   environment:
  #     - VITE_DB_HOST=postgres
  #     - VITE_PG_HOST=postgres-database
  #   command: db migrations bootstrap









  backend:
      container_name: backend
      build: ./backend/
      restart: always
      ports:
        - "8080:8080"
      environment:
        - VITE_DB_HOST=postgres
        - VITE_IP_ADDR=0.0.0.0
        - VITE_PORT=8080
        - VITE_LOGS_DIR=logs/
        - VITE_DB_PORT=5432
        - VITE_DB_USER=clickers
        - VITE_DB_PASS=clickers
        - VITE_DB_NAME=clickers
      depends_on:
        postgres:
          condition: service_healthy


  postgres:  
      container_name: postgres
      image: postgres:15-alpine
      restart: always
      ports:
        - "5432:5432" 
      volumes:
        - db:/var/lib/postgresql/data
      environment:
        - POSTGRES_USER=clickers
        - POSTGRES_PASSWORD=clickers
        - POSTGRES_DB=clickers
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U clickers"]
        interval: 10s
        timeout: 5s
        retries: 5

  # frontend:
  #   container_name: frontend
  #   build: ./frontend/
  #   restart: always
  #   ports:
  #     - "88:80" # We need to map here for convenience, 
  #     # so we don't conflict with a potential possible local server
  #   environment:
  #     - VITE_BACKEND_IP=127.0.0.1
  #     - VITE_BACKEND_PORT=8080


  # minio:
  #   container_name: minio
  #   image: docker.io/bitnami/minio:latest
  #   ports:
  #     - "9000:9000"
  #     - "9001:9001"
  #   environment:
  #     - MINIO_DEFAULT_BUCKETS=hola:public
  #     - MINIO_ROOT_USER=clickers
  #     - MINIO_ROOT_PASSWORD=clickersPass
  #     - MINIO_SERVER_ACCESS_KEY=clickers
  #     - MINIO_SERVER_SECRET_KEY=clickersPass
  #   volumes:
  #     - minio_data:/data
volumes:
  # minio_data:
  #   driver: local
  db:
    driver: local
