version: '3'
services:
  backend:
      container_name: backend
      build: ./backend/
      restart: always
      ports:
        - "8080:8080"
      environment:
        - VITE_DB_HOST=postgres
        - VITE_IP_ADDR=0.0.0.0
        - VITE_PORT=8080
        - VITE_LOGS_DIR=logs/
        - VITE_DB_PORT=5433
        - VITE_DB_USER=clickers
        - VITE_DB_PASS=clickers
        - VITE_DB_NAME=clickers
      depends_on:
        - postgres
  postgres:
      container_name: postgres
      image: postgres:15-alpine
      restart: always
      ports:
        - "5433:5432" 
      volumes:
        - db:/var/lib/postgresql/data
      environment:
        - POSTGRES_USER=clickers
        - POSTGRES_PASSWORD=clickers
        - POSTGRES_DB=clickers


  frontend:
    container_name: frontend
    build: ./frontend/
    restart: always
    ports:
      - "88:80" # We need to map here for convenience, 
      # so we don't conflict with a potential possible local server
    environment:
      - VITE_BACKEND_IP=backend
      - VITE_BACKEND_PORT=8080


  minio:
    container_name: minio
    image: docker.io/bitnami/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_DEFAULT_BUCKETS=clickerGame:public
      - MINIO_ROOT_USER=clickers
      - MINIO_ROOT_PASSWORD=clickersPass
      - MINIO_SERVER_ACCESS_KEY=clickers
      - MINIO_SERVER_SECRET_KEY=clickersPass
    volumes:
      - minio_data:/data
volumes:
  minio_data:
    driver: local
  db:
    driver: local
